# Stubs for alembic.testing.assertions (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..util.compat import py3k
from typing import Any, Optional

def eq_ignore_whitespace(a: Any, b: Any, msg: Optional[Any] = ...) -> None: ...
def expect_warnings(*messages: Any, **kw: Any): ...
def emits_python_deprecation_warning(*messages: Any): ...
