# Stubs for alembic.testing.env (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..script import Script, ScriptDirectory
from ..util.compat import get_current_bytecode_suffixes, has_pep3147, u
from typing import Any


def staging_env(create: bool = ..., template: str = ..., sourceless: bool = ...):
    ...


def clear_staging_env() -> None:
    ...


def script_file_fixture(txt: Any) -> None:
    ...


def env_file_fixture(txt: Any) -> None:
    ...


def write_script(scriptdir: Any, rev_id: Any, content: Any, encoding: str = ..., sourceless: bool = ...) -> None:
    ...


def make_sourceless(path: Any, style: Any) -> None:
    ...


def three_rev_fixture(cfg: Any):
    ...


def multi_heads_fixture(cfg: Any, a: Any, b: Any, c: Any):
    ...
