# Stubs for alembic.testing.fixtures (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..environment import EnvironmentContext
from ..migration import MigrationContext
from ..operations import Operations
from ..util import compat
from ..util.compat import configparser, string_types, text_type
from ..util.sqla_compat import create_mock_engine
from .assertions import _get_dialect
from typing import Any, Optional

testing_config: Any


def capture_db(dialect: str = ...):
    ...


def capture_context_buffer(**kw: Any):
    ...


def capture_engine_context_buffer(**kw: Any):
    ...


def op_fixture(dialect: str = ...,
               as_sql: bool = ...,
               naming_convention: Optional[Any] = ...,
               literal_binds: bool = ...,
               native_boolean: Optional[Any] = ...):
    ...


class AlterColRoundTripFixture:
    __requires__: Any = ...
    conn: Any = ...
    ctx: Any = ...
    op: Any = ...
    metadata: Any = ...

    def setUp(self) -> None:
        ...

    def tearDown(self) -> None:
        ...
