# Stubs for alembic.testing.requirements (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from sqlalchemy.testing.requirements import Requirements


class SuiteRequirements(Requirements):

    @property
    def schemas(self):
        ...

    @property
    def autocommit_isolation(self):
        ...

    @property
    def unique_constraint_reflection(self):
        ...

    @property
    def foreign_key_match(self):
        ...

    @property
    def check_constraints_w_enforcement(self):
        ...

    @property
    def reflects_pk_names(self):
        ...

    @property
    def reflects_fk_options(self):
        ...

    @property
    def sqlalchemy_issue_3740(self):
        ...

    @property
    def sqlalchemy_12(self):
        ...

    @property
    def sqlalchemy_13(self):
        ...

    @property
    def sqlalchemy_1115(self):
        ...

    @property
    def sqlalchemy_110(self):
        ...

    @property
    def sqlalchemy_issue_4436(self):
        ...

    @property
    def python3(self):
        ...

    @property
    def pep3147(self):
        ...

    @property
    def comments(self):
        ...

    @property
    def comments_api(self):
        ...

    @property
    def alter_column(self):
        ...
