# Stubs for absl.logging.converter (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

STANDARD_CRITICAL: Any
STANDARD_ERROR: Any
STANDARD_WARNING: Any
STANDARD_INFO: Any
STANDARD_DEBUG: Any
ABSL_FATAL: int
ABSL_ERROR: int
ABSL_WARNING: int
ABSL_WARN: int
ABSL_INFO: int
ABSL_DEBUG: int
ABSL_LEVELS: Any
ABSL_NAMES: Any
ABSL_TO_STANDARD: Any
STANDARD_TO_ABSL: Any


def get_initial_for_level(level: Any):
    ...


def absl_to_cpp(level: Any):
    ...


def absl_to_standard(level: Any):
    ...


def string_to_standard(level: Any):
    ...


def standard_to_absl(level: Any):
    ...


def standard_to_cpp(level: Any):
    ...
