class Log:
  def __init__(self, **kwargs) -> None: ...
class Babble:
  def __init__(self, **kwargs) -> None: ...
class Babble2:
  def __init__(self, **kwargs) -> None: ...
class Babble_count:
  def __init__(self, **kwargs) -> None: ...
class Babble_last:
  def __init__(self, **kwargs) -> None: ...
class UrbanBlacklist:
  def __init__(self, **kwargs) -> None: ...
class Commands:
  def __init__(self, **kwargs) -> None: ...
class Urls:
  def __init__(self, **kwargs) -> None: ...
class Scores:
  def __init__(self, **kwargs) -> None: ...
class Notes:
  def __init__(self, **kwargs) -> None: ...
class Polls:
  def __init__(self, **kwargs) -> None: ...
class Poll_responses:
  def __init__(self, **kwargs) -> None: ...
class Tumblrs:
  def __init__(self, **kwargs) -> None: ...
class Stopwatches:
  def __init__(self, **kwargs) -> None: ...
class Quotes:
  def __init__(self, **kwargs) -> None: ...
class Issues:
  def __init__(self, **kwargs) -> None: ...
class Ignore:
  def __init__(self, **kwargs) -> None: ...
class Weather_prefs:
  def __init__(self, **kwargs) -> None: ...

def setup_db(session, botconfig, confdir) -> None: ...
