from sqlalchemy import Column, UnicodeText, Unicode, Integer, DateTime
class Base:
  def __init__(self, *args, **kwargs) -> None: ...
class Log(Base):
  source = Column(UnicodeText)
  target = Column(Unicode(length=512), index=True)
  flags = Column(Integer)
  msg = Column(UnicodeText)
  type = Column(UnicodeText)
  time = Column(DateTime)
class Babble(Base): ...
class Babble2(Base): ...
class Babble_count(Base): ...
class Babble_last(Base): ...
class UrbanBlacklist(Base): ...
class Commands(Base): ...
class Urls(Base): ...
class Scores(Base): ...
class Notes(Base): ...
class Polls(Base): ...
class Poll_responses(Base): ...
class Tumblrs(Base): ...
class Stopwatches(Base): ...
class Quotes(Base): ...
class Issues(Base): ...
class Ignore(Base): ...
class Weather_prefs(Base): ...
class Permissions(Base): ...

def setup_db(session, botconfig: str, confdir: str) -> None: ...
