#!/bin/bash
set -e

function handle_docs() {
cd gh-pages
../scripts/gendocs.sh
git add .
if ! [ -z "`git status --porcelain`" ]; then
	git commit -m 'update docs'
fi
git push
cd ..
}

# do docs
# handle_docs

# update master
git submodule update --remote
git pull --ff-only

# push to github
git push

./scripts/reload

cd /home/ircbot/bot
sudo -u ircbot (git submodule update --remote && git pull)
if [ "$1" == "restart" ]; then
	sudo /etc/init.d/ircbot restart
else
	sudo -u ircbot ./scripts/reload
fi

