#!/bin/bash
set -e

# push to github
git push

# do docs
cd gh-pages
../gendocs.sh
git add .
if ! [ -z "`git status --porcelain`" ]; then
	git commit -m 'update docs'
fi
git push
cd ..

# update master ro dev
git checkout master
git pull
if ! git merge --ff-only dev; then
	git checkout dev
	figlet Please rebase dev
	exit 1
fi
git push
git checkout dev
cd /home/ircbot/bot
sudo -u ircbot git pull
sudo -u ircbot ./reload.py
