#!/bin/bash
set -e

# do docs
# handle_docs
# update master to dev
git checkout master
git pull
if ! git merge --ff-only dev; then
	git checkout dev
	figlet Please rebase dev
	exit 1
fi
git checkout dev

# push to github
git push --all

./scripts/reload

cd /home/ircbot/bot
sudo -u ircbot git pull
if [ "$1" == "restart" ]; then
	sudo /etc/init.d/ircbot restart
else
	sudo -u ircbot ./scripts/reload
fi

function handle_docs() {
cd gh-pages
../scripts/gendocs.sh
git add .
if ! [ -z "`git status --porcelain`" ]; then
	git commit -m 'update docs'
fi
git push
cd ..
}
