from typing import Tuple

class ThreadingMixIn: ...
class TCPServer:
  def __init__(self, server_address: Tuple[str, int], request_handler: BaseRequestHandler) -> None: ...
class BaseRequestHandler: ...
