# Stubs for packaging._compat (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

PY2 = ...  # type: Any
PY3 = ...  # type: Any
string_types = ...  # type: Any

def with_metaclass(meta, *bases): ...
