# Stubs for packaging.requirements (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from pyparsing import Literal as L
from six.moves.urllib import parse as urlparse
from .markers import Marker as Marker
from .specifiers import LegacySpecifier as LegacySpecifier, Specifier as Specifier, SpecifierSet as SpecifierSet

class InvalidRequirement(ValueError): ...

ALPHANUM = ...  # type: Any
LBRACKET = ...  # type: Any
RBRACKET = ...  # type: Any
LPAREN = ...  # type: Any
RPAREN = ...  # type: Any
COMMA = ...  # type: Any
SEMICOLON = ...  # type: Any
AT = ...  # type: Any
PUNCTUATION = ...  # type: Any
IDENTIFIER_END = ...  # type: Any
IDENTIFIER = ...  # type: Any
NAME = ...  # type: Any
EXTRA = ...  # type: Any
URI = ...  # type: Any
URL = ...  # type: Any
EXTRAS_LIST = ...  # type: Any
EXTRAS = ...  # type: Any
VERSION_PEP440 = ...  # type: Any
VERSION_LEGACY = ...  # type: Any
VERSION_ONE = ...  # type: Any
VERSION_MANY = ...  # type: Any
VERSION_SPEC = ...  # type: Any
MARKER_SEPERATOR = ...  # type: Any
MARKER_EXPR = ...  # type: Any
MARKER = ...  # type: Any
VERSION_AND_MARKER = ...  # type: Any
URL_AND_MARKER = ...  # type: Any
NAMED_REQUIREMENT = ...  # type: Any
REQUIREMENT = ...  # type: Any

class Requirement:
    name = ...  # type: Any
    url = ...  # type: Any
    extras = ...  # type: Any
    specifier = ...  # type: Any
    marker = ...  # type: Any
    def __init__(self, requirement_string): ...
