# Stubs for alembic.command (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .runtime.environment import EnvironmentContext as EnvironmentContext
from .config import Config


def list_templates(config):
    ...


def init(config, directory, template=''):
    ...


def revision(config,
             message=None,
             autogenerate=False,
             sql=False,
             head='',
             splice=False,
             branch_label=None,
             version_path=None,
             rev_id=None,
             depends_on=None):
    ...


def merge(config, revisions, message=None, branch_label=None, rev_id=None):
    ...


def upgrade(config: Config, revision: str, tag='', sql=False) -> None:
    ...


def downgrade(config, revision, sql=False, tag=None):
    ...


def show(config, rev):
    ...


def history(config, rev_range=None, verbose=False):
    ...


def heads(config, verbose=False, resolve_dependencies=False):
    ...


def branches(config, verbose=False):
    ...


def current(config, verbose=False, head_only=False):
    ...


def stamp(config, revision, sql=False, tag=None):
    ...


def edit(config, rev):
    ...
