# Stubs for alembic.config (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
#from .util.compat import SafeConfigParser as SafeConfigParser
#from .util import compat as compat


class Config:
    config_file_name = ...  # type: Any
    config_ini_section = ...  # type: Any
    output_buffer = ...  # type: Any
    stdout = ...  # type: Any
    cmd_opts = ...  # type: Any
    config_args = ...  # type: Any

    def __init__(self, file_=None, ini_section='', output_buffer=None, stdout=..., cmd_opts=None, config_args=..., attributes=None) -> None:
        ...

    def attributes(self):
        ...

    def print_stdout(self, text, *arg):
        ...

    def file_config(self):
        ...

    def get_template_directory(self):
        ...

    def get_section(self, name):
        ...

    def set_main_option(self, name: str, value: str) -> None:
        ...

    def remove_main_option(self, name):
        ...

    def set_section_option(self, section, name, value):
        ...

    def get_section_option(self, section, name, default=None):
        ...

    def get_main_option(self, name, default=None):
        ...


class CommandLine:

    def __init__(self, prog=None):
        ...

    def run_cmd(self, config, options):
        ...

    def main(self, argv=None):
        ...


def main(argv=None, prog=None, **kwargs):
    ...
