# Stubs for alembic.util (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .langhelpers import asbool as asbool, rev_id as rev_id, to_tuple as to_tuple, to_list as to_list, memoized_property as memoized_property, dedupe_tuple as dedupe_tuple, immutabledict as immutabledict, _with_legacy_names as _with_legacy_names, Dispatcher as Dispatcher, ModuleClsProxy as ModuleClsProxy
from .messaging import write_outstream as write_outstream, status as status, err as err, obfuscate_url_pw as obfuscate_url_pw, warn as warn, msg as msg, format_as_comma as format_as_comma
from .pyfiles import template_to_file as template_to_file, coerce_resource_to_filename as coerce_resource_to_filename, simple_pyc_file_from_path as simple_pyc_file_from_path, pyc_file_from_path as pyc_file_from_path, load_python_file as load_python_file, edit as edit
from .sqla_compat import sqla_07 as sqla_07, sqla_079 as sqla_079, sqla_08 as sqla_08, sqla_083 as sqla_083, sqla_084 as sqla_084, sqla_09 as sqla_09, sqla_092 as sqla_092, sqla_094 as sqla_094, sqla_099 as sqla_099, sqla_100 as sqla_100, sqla_105 as sqla_105, sqla_110 as sqla_110
from .exc import CommandError as CommandError
