# Stubs for alembic.util.pyfiles (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .compat import load_module_py as load_module_py, load_module_pyc as load_module_pyc
from .exc import CommandError as CommandError


def template_to_file(template_file, dest, output_encoding, **kw):
    ...


def coerce_resource_to_filename(fname):
    ...


def simple_pyc_file_from_path(path):
    ...


def pyc_file_from_path(path):
    ...


def edit(path):
    ...


def load_python_file(dir_, filename):
    ...
