# Stubs for alembic.util.sqla_compat (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from sqlalchemy import sql
from sqlalchemy.sql.expression import _BindParamClause
from typing import Any

sqla_110: Any
sqla_1115: Any
sqla_120: Any
sqla_1216: Any
sqla_13: Any
sqla_14: Any
AUTOINCREMENT_DEFAULT: str


class _textual_index_element(sql.ColumnElement):
    __visit_name__: str = ...
    table: Any = ...
    text: Any = ...
    key: Any = ...
    fake_column: Any = ...

    def __init__(self, table: Any, text: Any) -> None:
        ...

    def get_children(self):
        ...


class _literal_bindparam(_BindParamClause):
    ...
