# Stubs for alembic.autogenerate.render (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..operations import ops
from ..util import compat, sqla_compat
from ..util.compat import StringIO, string_types
from typing import Any

MAX_PYTHON_ARGS: int
default_renderers: Any
renderers: Any


def render_op(autogen_context: Any, op: Any):
    ...


def render_op_text(autogen_context: Any, op: Any):
    ...


class _f_name:
    prefix: Any = ...
    name: Any = ...

    def __init__(self, prefix: Any, name: Any) -> None:
        ...
