# Stubs for alembic.autogenerate.rewriter (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any


class Rewriter:
    dispatch: Any = ...

    def __init__(self) -> None:
        ...

    def chain(self, other: Any):
        ...

    def rewrites(self, operator: Any):
        ...

    def __call__(self, context: Any, revision: Any, directives: Any) -> None:
        ...

    def process_revision_directives(self, context: Any, revision: Any, directives: Any) -> None:
        ...
