"""initial commit

Revision ID: ef7ccebeff
Revises: 
Create Date: 2015-04-15 14:08:17.427330

"""

# revision identifiers, used by Alembic.
revision = 'ef7ccebeff'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_babble_key', table_name='babble')
    op.add_column('issues', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('issues', 'desc')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('desc', sa.NUMERIC(), nullable=True))
    op.drop_column('issues', 'description')
    op.create_index('ix_babble_key', 'babble', ['key'], unique=False)
    ### end Alembic commands ###
