# Stubs for irc.connection (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from socket import socket
from typing import Any, Callable

identity = ...  # type: Any

class Factory:
    family = ...  # type: Any
    bind_address = ...  # type: Any
    wrapper = ...  # type: Any
    def __init__(self, bind_address: str = None, wrapper: Callable[..., socket] = None, ipv6=False) -> None: ...
    def connect(self, server_address): ...
    __call__ = ...  # type: Any
