# Stubs for irc.dict (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from jaraco.collections import KeyTransformingDict

class IRCDict(KeyTransformingDict):
    @staticmethod
    def transform_key(key): ...
