from datetime import datetime
from typing import Any
def or_(*clauses): ...
def create_engine(*args: Any, **kwargs: Any): ...
class Column:
  def __init__(self, *args, **kwargs) -> None: ...
  def __ge__(self, other): ...
  def desc(self) -> Any: ...
class UnicodeText(Column): ...
class Unicode(Column): ...
class DateTime(Column): ...
class Integer(Column): ...
class Index:
  def __init__(self, name, *expressions, **kwargs) -> None: ...
