from datetime import datetime
def or_(*clauses): ...
def create_engine(*args, **kwargs): ...
class Column:
  def __init__(self, *args, **kwargs) -> None: ...
  def __ge__(self, other): ...
  def desc(self): ...
class UnicodeText(Column): ...
class Unicode(Column): ...
class DateTime(Column): ...
class Integer(Column): ...
class Index:
  def __init__(self, name, *expressions, **kwargs) -> None: ...
