from typing import Generic, TypeVar

class sessionmaker:
  def __init__(self, bind) -> None: ...

T = TypeVar('T')

class Query(Generic[T]):
  def filter(self, *criterion) -> Query: ...
  def order_by(self, *criterion) -> Query: ...
  def offset(self, offset) -> Query: ...
  def first(self) -> T: ...
class Session:
  def add(self, instance) -> None: ...
  def query(self, table: T, **kwargs) -> Query[T]: ...
