# Stubs for alembic.script.write_hooks (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..util import compat
from typing import Any


def register(name: Any):
    ...


def console_scripts(path: Any, options: Any) -> None:
    ...
