# Stubs for alembic.operations.base (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .. import util
from typing import Any, Optional


class Operations(util.ModuleClsProxy):
    migration_context: Any = ...
    impl: Any = ...
    schema_obj: Any = ...

    def __init__(self, migration_context: Any, impl: Optional[Any] = ...) -> None:
        ...

    @classmethod
    def register_operation(cls, name: Any, sourcename: Optional[Any] = ...):
        ...

    @classmethod
    def implementation_for(cls, op_cls: Any):
        ...

    @classmethod
    def context(cls, migration_context: Any) -> None:
        ...

    def batch_alter_table(self,
                          table_name: Any,
                          schema: Optional[Any] = ...,
                          recreate: str = ...,
                          copy_from: Optional[Any] = ...,
                          table_args: Any = ...,
                          table_kwargs: Any = ...,
                          reflect_args: Any = ...,
                          reflect_kwargs: Any = ...,
                          naming_convention: Optional[Any] = ...) -> None:
        ...

    def get_context(self):
        ...

    def invoke(self, operation: Any):
        ...

    def f(self, name: Any):
        ...

    def inline_literal(self, value: Any, type_: Optional[Any] = ...):
        ...

    def get_bind(self):
        ...


class BatchOperations(Operations):
    ...
