#!/bin/bash
PASSWORD=`python -c 'import configparser;cfg=configparser.ConfigParser();cfg.read("config.cfg");print(cfg["auth"]["ctrlpass"])'`
PORT=`python -c 'import configparser;cfg=configparser.ConfigParser();cfg.read("config.cfg");print(cfg["core"]["serverport"])'`
echo -e "$PASSWORD\nreload" | nc localhost $PORT
