# Stubs for absl.flags (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

DEFINE: Any
DEFINE_flag: Any
DEFINE_string: Any
DEFINE_boolean: Any
DEFINE_bool = DEFINE_boolean
DEFINE_float: Any
DEFINE_integer: Any
DEFINE_enum: Any
DEFINE_enum_class: Any
DEFINE_list: Any
DEFINE_spaceseplist: Any
DEFINE_multi: Any
DEFINE_multi_string: Any
DEFINE_multi_integer: Any
DEFINE_multi_float: Any
DEFINE_multi_enum: Any
DEFINE_multi_enum_class: Any
DEFINE_alias: Any
register_validator: Any
validator: Any
register_multi_flags_validator: Any
multi_flags_validator: Any
mark_flag_as_required: Any
mark_flags_as_required: Any
mark_flags_as_mutual_exclusive: Any
mark_bool_flags_as_mutual_exclusive: Any
declare_key_flag: Any
adopt_module_key_flags: Any
disclaim_key_flags: Any
Error: Any
CantOpenFlagFileError: Any
DuplicateFlagError: Any
IllegalFlagValueError: Any
UnrecognizedFlagError: Any
UnparsedFlagAccessError: Any
ValidationError: Any
FlagNameConflictsWithMethodError: Any
Flag: Any
BooleanFlag: Any
EnumFlag: Any
EnumClassFlag: Any
MultiFlag: Any
MultiEnumClassFlag: Any
FlagValues: Any
ArgumentParser: Any
BooleanParser: Any
EnumParser: Any
EnumClassParser: Any
ArgumentSerializer: Any
FloatParser: Any
IntegerParser: Any
BaseListParser: Any
ListParser: Any
ListSerializer: Any
CsvListSerializer: Any
WhitespaceSeparatedListParser: Any
get_help_width: Any
text_wrap: Any
flag_dict_to_args: Any
doc_to_help: Any
FLAGS: Any
