# Stubs for absl.flags._exceptions (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional


class Error(Exception):
    ...


class CantOpenFlagFileError(Error):
    ...


class DuplicateFlagError(Error):

    @classmethod
    def from_flag(cls, flagname: Any, flag_values: Any, other_flag_values: Optional[Any] = ...):
        ...


class IllegalFlagValueError(Error):
    ...


class UnrecognizedFlagError(Error):
    flagname: Any = ...
    flagvalue: Any = ...

    def __init__(self, flagname: Any, flagvalue: str = ..., suggestions: Optional[Any] = ...) -> None:
        ...


class UnparsedFlagAccessError(Error):
    ...


class ValidationError(Error):
    ...


class FlagNameConflictsWithMethodError(Error):
    ...
