# Stubs for absl.command_name (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def make_process_name_useful() -> None: ...
def set_kernel_process_name(name: Any): ...
